version: '3.3'

services:
  telegram-bot:
    image: wolke77/alertmanager-telegram-bot:0.0.3
    build: .
    volumes:
      - ./telegrambot/:/etc/telegrambot/
    expose:
      - 9087
    ports:
      - 127.0.0.1:9087:9087
    restart: always
    command:  ["/prometheus_bot", "-c", "/etc/telegrambot/config.yaml", "-d"]
